//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace developerBackEndTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class diamondEntities : DbContext
    {
        public diamondEntities()
            : base("name=diamondEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ItemPhotoPropertySet> ItemPhotoPropertySets { get; set; }
        public virtual DbSet<ItemPhoto> ItemPhotos { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<TypePropertySet> TypePropertySets { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}
